### ISSUE TITLE
Docs for NICE interface

### ISSUE THREAD

**Issue by mfkiwl** [riscv-mcu/e203_hbirdv2#1]
Thank you very much for sharing the revised version of E203. It is nice to have the NICE co-processor interface included in your code.

The problem now is how to write users' own co-processors/accelerators. Any Docs on the NICE interface? It will be best if examples can be included.

Regards,
Xing

**Comment by hucan7** [comment]
> Thank you very much for sharing the revised version of E203. It is nice to have the NICE co-processor interface included in your code.
> The problem now is how to write users' own co-processors/accelerators. Any Docs on the NICE interface? It will be best if examples can be included.
> Regards,
> Xing

We will provide a simple user case for NICE co-processing, and the related document is ongoing... When it's ready, I will update that in README.

Thanks,
Hu Can

**Comment by fanghuaqi** [comment]
See https://doc.nucleisys.com/hbirdv2
