### ISSUE TITLE
Nuclei Studio IDE User guide for e203_hbirdv2 is not update to date 蜂鸟二代IDE使用文档对不上

### ISSUE THREAD

**Issue by fanghuaqi** [riscv-mcu/e203_hbirdv2#10]
根据文档所描述的 https://doc.nucleisys.com/hbirdv2/quick_start/ide.html 下载IDE，发现没法和最新的IDE匹配上请更新。

这里的文档能匹配的应该是 2020.09版本 

![image](https://user-images.githubusercontent.com/1538922/187588213-823f21d6-6d12-4bf6-ba1b-15d2a3b95931.png)

![image](https://user-images.githubusercontent.com/1538922/187584213-986db303-ccbe-46b1-9128-72975893cfee.png)

最新的 2022.04版本无法正常使用，最新的版本使用的是NPK方式，请参照IDE文档。 

蜂鸟v1/v2这里采用的hbird-sdk的NPK包，可以从https://github.com/riscv-mcu/hbird-sdk/releases/tag/0.1.3 这里下载zip包，然后通过Nuclei Package Management导入，然后使用Create Nuclei RISC-V C/C++ Project选择HummingBird对应的开发板和SoC创建对应的使用用例。

**Comment by fanghuaqi** [comment]
About Nuclei NPK package, please check https://github.com/Nuclei-Software/nuclei-sdk/wiki/Nuclei-Available-NPK-Zips

**Comment by fanghuaqi** [comment]
下面步骤适用于 2022.04/08版本的Nuclei Studio

1. 下载 hbird-sdk的npk包

![image](https://user-images.githubusercontent.com/1538922/187593257-04c77989-a56a-4a7b-95fa-e7da3c8a602a.png)

2. 如果使用蜂鸟2代，选择v2的SoC

![image](https://user-images.githubusercontent.com/1538922/187593393-da285b75-0c0b-4bc6-b0c9-333c239f891e.png)

3. 创建helloworld示例

![image](https://user-images.githubusercontent.com/1538922/187593466-b2db8dec-24a1-4dd4-9609-3cc3bd3bca32.png)

**Comment by hucan7** [comment]
Doc has been updated.
https://doc.nucleisys.com/hbirdv2/quick_start/ide_latest.html#
