### ISSUE TITLE
关于移植到xc7z100ffg9-2出现的问题

### ISSUE THREAD

**Issue by Fahrenhell** [riscv-mcu/e203_hbirdv2#17]
您好，我想请教一下，我现在把e203移植到另外一块开发板出现了以下的问题：
1、由于这块开发板的特殊性，上面的32.768KHz时钟不能供给PL端使用，所以vivado在综合的时候，这条时序路径会报错。这个问题该怎么解决？是可以忽略的吗？
2、移植过去之后，我把jtag接口和gpioA上的uart接口引了出来但是出现了以下报错：

![屏幕截图_20221229_100736](https://user-images.githubusercontent.com/111461099/209894106-74c3ccb2-1e81-4b0a-8b74-5423cb1aa0b3.png)
为什么会没有检测到内核？

**Comment by Fahrenhell** [comment]
我突然有个想法，不会是蜂鸟jtag调试器不支持xc7z100ffg9-2吧？

**Comment by fanghuaqi** [comment]
可以去社区问问其他人 https://www.rvmcu.com/community-show-id-2.html

> 我突然有个想法，不会是蜂鸟jtag调试器不支持xc7z100ffg9-2吧？

蜂鸟调试器不存在不支持特定fpga的说法，一般都是自己移植没到位。

**Comment by Fahrenhell** [comment]
那我再问一下，蜂鸟jtag调试器上面的uart tx和rx是连到gpioA的17和16吗？gpioA的其他引脚会影响jtag吗？因为我不想用那么多gpioA上的引脚，所以就只引了uart出来。

**Comment by fanghuaqi** [comment]
> 那我再问一下，蜂鸟jtag调试器上面的uart tx和rx是连到gpioA的17和16吗？gpioA的其他引脚会影响jtag吗？因为我不想用那么多gpioA上的引脚，所以就只引了uart出来。

这个我不了解，建议仔细阅读代码和相关文档。

**Comment by Fahrenhell** [comment]
那除了使用jtag，还有什么其他的办法可以知道e203跑起来了呢？

**Comment by fanghuaqi** [comment]
https://doc.nucleisys.com/hbirdv2/quick_start/index.html

**Comment by Fahrenhell** [comment]
这不是还是要用jtag？
