### ISSUE TITLE
跑仿真遇到的一些问题

### ISSUE THREAD

**Issue by cyl-0411** [riscv-mcu/e203_hbirdv2#19]
#### 1.README存在一些小问题
`/e203_hbirdv2/vsim/README.md`中的第十四行:
原代码：`make compile SIM=iverlog **or** make compile SIM=VCS`
这里的的`iverilog`少了个`i`。

#### 2.对于Ubuntu22.04需要进行额外配置
我进行到`4.1.3. Run simulation tests`时，执行`make run_test SIM=iverilog`命令时报错，报错信息：`Syntax error: "&"unexpected`。
我根据[这个](https://www.jianshu.com/p/89b40e01d983)解决了问题。希望可以将这个问题加入文档中，让以后走到这一步的同学少走一些弯路。

**Comment by fanghuaqi** [comment]
可以发个PR修复下 @cyl-0411

**Comment by mio-19** [comment]
https://github.com/riscv-mcu/e203_hbirdv2/commit/6502cfac733146ec02f6bef96b8f5f5cb006d5e4

**Comment by fanghuaqi** [comment]
Fixed by https://github.com/riscv-mcu/e203_hbirdv2/pull/21
