### ISSUE TITLE
求NICE接口搭载协处理器教程或者资源

### ISSUE THREAD

**Issue by ichxm** [riscv-mcu/e203_hbirdv2#24]
我正在学习如何在NICE接口搭载协处理器，比如乘法器+加法器+……，然后用自定义指令1、2……去调用他们，请问大家有没有相关教程，或者相关资源，万分感谢！@、

**Comment by fanghuaqi** [comment]
https://doc.nucleisys.com/hbirdv2/core/core.html#nice @ichxm

**Comment by fanghuaqi** [comment]
https://www.rvmcu.com/community-show-id-2.html 也可以在这里搜下历史的文章和问题
