### ISSUE TITLE
关于PLIC部分代码是否可综合问题（Is the plic code synthesizable ？ ）

### ISSUE THREAD

**Issue by clancylea** [riscv-mcu/e203_hbirdv2#9]
![1660269346660](https://user-images.githubusercontent.com/42167380/184270827-1880b5e8-1d01-48a6-bec3-a6a86402bafa.jpg)

please  ，Is the plic code synthesizable ？，Thanks！

**Comment by hucan7** [comment]
> ![1660269346660](https://user-images.githubusercontent.com/42167380/184270827-1880b5e8-1d01-48a6-bec3-a6a86402bafa.jpg)
> 
> please ，Is the plic code synthesizable ？，Thanks！

Of course，you can have a try，or what's the problem you have when you did the synthesize

**Comment by clancylea** [comment]
thank you，sir
